/**
 * @module src/agents/nodes/contentExecutor
 *
 * Content Executor Agent
 *
 * Responsibilities:
 *  1. Read the blueprint from the state (generated by Layout Executor).
 *  2. Iterate through each section in the blueprint.
 *  3. For each section, fetch its component description and compressed schema.
 *  4. Query the LLM to generate props strictly matching the schema.
 *  5. Validate and merge the generated props.
 *  6. Return the fully populated blueprint.
 */

import { ChatOpenAI } from "@langchain/openai";
import { SystemMessage, HumanMessage, AIMessage } from "@langchain/core/messages";
import type { GraphState } from "../state";
import type { SectionConfig } from "./layoutExecutor";
import { getCompressedSchema, getRegistryEntry } from "../../../registry/componentRegistry";
import { createLLM } from "../../lib/llm";

const CONTENT_SYSTEM = `You are the Content Executor for an AI website builder.

Your job is to generate content (props) for a specific UI component based on the user's requirements and the website plan.

Component: {COMPONENT_TYPE}
Description: {COMPONENT_DESCRIPTION}

Prop Schema (Required structure):
{COMPONENT_SCHEMA}

Output ONLY valid JSON representing the props object. Do NOT wrap it in markdown block, no explanation.

Rules:
- Generate meaningful, high-quality content that fits the user's requirements.
- Strictly follow the Prop Schema. Do not add hallucinated props.
- If a prop is an array, ensure it has sensible default items (e.g., 3 feature cards).
- Use proper names, professional tone, and match the specified style.`;

function buildContext(history: GraphState["history"], limit = 8) {
  return history.slice(-limit).map((m) =>
    m.role === "user" ? new HumanMessage(m.content) : new AIMessage(m.content)
  );
}

function parseJSON<T>(raw: string, fallback: T): T {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) return fallback;
  try {
    return JSON.parse(match[0]) as T;
  } catch {
    return fallback;
  }
}

export async function contentExecutorNode(state: GraphState): Promise<Partial<GraphState>> {
  const llm = createLLM();

  if (!state.blueprint || state.blueprint.length === 0) {
    return {
      errors: [...(state.errors || []), "Content Executor ran without a blueprint"],
      nextStep: "layout_executor",
    };
  }

  const requirementsSummary = [
    state.requirements?.websiteType && `Website Type: ${state.requirements.websiteType}`,
    state.requirements?.targetAudience && `Target Audience: ${state.requirements.targetAudience}`,
    state.requirements?.features?.length && `Features: ${state.requirements.features.join(", ")}`,
    state.requirements?.style && `Style: ${state.requirements.style}`,
    state.plan?.notes && `Plan Notes: ${state.plan.notes}`,
  ].filter(Boolean).join("\n");

  const populatedBlueprint: SectionConfig[] = [];

  for (const section of state.blueprint as SectionConfig[]) {
    const entry = getRegistryEntry(section.type);
    if (!entry) {
      // If somehow invalid, keep as is
      populatedBlueprint.push(section);
      continue;
    }

    const compressedSchema = getCompressedSchema(section.type) || {};
    
    const systemPrompt = CONTENT_SYSTEM
      .replace("{COMPONENT_TYPE}", section.type)
      .replace("{COMPONENT_DESCRIPTION}", entry.description)
      .replace("{COMPONENT_SCHEMA}", JSON.stringify(compressedSchema, null, 2));

    const res = await llm.invoke([
      new SystemMessage(systemPrompt),
      ...buildContext(state.history, 4),
      new HumanMessage(`Requirements Context:\n${requirementsSummary}\n\nGenerate props for the "${section.type}" component.`),
    ]);

    const generatedProps = parseJSON<Record<string, unknown>>(res.content as string, {});

    // Validation Layer: merge with defaultProps, keep only keys present in propSchema
    const validProps: Record<string, unknown> = { ...entry.defaultProps };
    
    for (const key of Object.keys(entry.propSchema)) {
      if (generatedProps[key] !== undefined) {
        validProps[key] = generatedProps[key];
      }
    }

    populatedBlueprint.push({
      ...section,
      props: validProps,
    });
  }

  return {
    blueprint: populatedBlueprint,
    currentStep: "content_executor",
    nextStep: "refiner", // Will point to human content feedback in graph edges
  };
}
